FROM node:24-alpine
ARG PM4_BRANCH=develop
ARG PM4_REPO=https://github.com/ProcessMaker/processmaker.git
WORKDIR /repo

RUN apk add git
RUN git clone --depth 1 --branch "${PM4_BRANCH}" --single-branch "${PM4_REPO}" .
RUN npm install
RUN NODE_OPTIONS="--max-old-space-size=8000" npm run prod