appVersion: {{IMAGE_TAG}}
eksCluster: pm4-eng
appConfig:
  https: false
  subdomain: .engk8s.processmaker.net
  customSecurityPolicy: true
  customSecurityPolicyUrl: 'https://adobexdplatform.com https://*.quicksight.aws.amazon.com https://www.canva.com https://excalidraw.com https://www.figma.com https://flocus.com https://www.framer.com https://giphy.com https://lookerstudio.google.com https://maps.google.com https://docs.google.com https://www.loom.com https://miro.com https://mixpanel.com https://pitch.com https://prezi.com https://www.sketch.com https://www.slideshare.net https://supademo.com https://www.tableau.com https://forms.app https://vimeo.com https://www.youtube.com'
  licenseRepo: processmaker/customer-licenses.git
  licenseBranch: production
  licenseGitToken: {{CUSTOMER_LICENSES_PAT}}
deploy:
  pmai:
    openaiHost: pmai-svc.pmai-system.svc.cluster.local
    deployDb: false
    dbHost: pm4-eng-stm-rds-cluster.cluster-ckz0mnb6cuna.us-east-1.rds.amazonaws.com
    dbName: pm4_ci-{{INSTANCE}}_ai
    dbUsername: user_ci-{{INSTANCE}}_ai
    dbPassword: {{MYSQL_PASSWORD}}
  volumes:
    storageClassName: 'efs-sc'
    storage:
      diskSize: 1Gi
  executor:
    diskSize: 10Gi
  resources:
    # Add resources step on Deployments
    # Executor - Scheduler - Queue - Web-UI
    enable: false  
database:
  deploy: false
  host: pm4-eng-stm-rds-cluster.cluster-ckz0mnb6cuna.us-east-1.rds.amazonaws.com
  name: pm4_ci-{{INSTANCE}}
  username: user_ci-{{INSTANCE}}
  password: {{MYSQL_PASSWORD}}
analytics:
  awsRegion: us-east-1
  awsS3Bucket: tmp-security-logs-to-download
  intercom:
    appId: memgomb2
    company: ENG
    env: ENG
    identityKey: sooZOeIDJI02_388erBqFH4PtbF_aflV--r4Fjmr
  logrocket:
    enable: false
    appId: gbuoqe/processmaker-4
  dashboard: https://us-east-1.quicksight.aws.amazon.com/sn/embed/share/accounts/780138555770/dashboards/a0194bdc-a1a6-4414-85a2-ab652ded98e3?directory_alias=processmaker
collaborativeModeler:
  host: socketio-dev.processmaker.net
  port: 443
cdata:
  connectors:
    docusign: 5543444B5541535544424141454E545041325246353431324354303100000000000000000000000050524F434553534D00004645344A374E443159345A550000
    excel: 5258444B5541535544424141454E545041325246353431324354303100000000000000000000000050524F434553534D00005A395A42364A5944463452350000
    github: 4647444B5541535544424141454E545041325246353431324354303100000000000000000000000050524F434553534D000056424530563739353759384A0000
    slack: 4643444B5541535544424141454E545041325246353431324354303100000000000000000000000050524F434553534D00004635523734413735455A32360000
    gmail: 4431444B5541535544424141454E545041325246353431324354303100000000000000000000000050524F434553534D00005356434441465847303144570000
    api: 4641444B5541535544424141454E545041325246353431324354303100000000000000000000000050524F434553534D00004750533442365456343939530000
microservices:
  scriptExecutor:
    enable: true
    customExecutors: false
    baseUrl: https://script-microsvr-us-east-1.processmaker.net
    version: v4.13.1
    keycloakClientId: microservices
    keycloakClientSecret: {{KEYCLOAK_CLIENT_SECRET}}
    keycloakBaseUrl: https://sso-microsvr-us-east-1.processmaker.net/realms/master/protocol/openid-connect/token
    keycloakUsername: pminstance-us-east-1
    keycloakPassword: {{KEYCLOAK_PASSWORD}}
twilio:
  enable: true
  phoneNumber: "+17243958155"
redis:
  diskSize: 2Gi
cicd: true
otel: true
loki: true
s3Backup:
  # Deploy S3 Backup CronJob
  deploy: false
stm:
  enable: false
